// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *InsertBasicSingle2Query) Exec(c gosql.Conn) error {
	const queryString = `INSERT INTO "column_tests_3" (
		"color_text"
		, "color_enum"
		, "some_time"
	) VALUES (
		NULLIF($1, '')::text
		, $2
		, $3
	)` // `

	_, err := c.Exec(queryString,
		q.Rel.ColorText,
		q.Rel.ColorEnum,
		q.Rel.SomeTime,
	)
	return err
}
