// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *InsertDefaultAllReturningSingleQuery) Exec(c gosql.Conn) error {
	const queryString = `INSERT INTO "test_user_with_defaults" AS u (
		"email"
		, "full_name"
		, "is_active"
		, "created_at"
		, "updated_at"
	) VALUES (
		DEFAULT
		, DEFAULT
		, DEFAULT
		, DEFAULT
		, DEFAULT
	)
	RETURNING
	u."id"
	, u."email"
	, u."full_name"
	, u."is_active"
	, u."created_at"
	, u."updated_at"` // `

	row := c.QueryRow(queryString)
	return row.Scan(
		&q.User.Id,
		&q.User.Email,
		&q.User.FullName,
		&q.User.IsActive,
		&q.User.CreatedAt,
		&q.User.UpdatedAt,
	)
}
