// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *InsertDefaultAllReturningSliceQuery) Exec(c gosql.Conn) error {
	var queryString = `INSERT INTO "test_user_with_defaults" AS u (
		"email"
		, "full_name"
		, "is_active"
		, "created_at"
		, "updated_at"
	) VALUES ` // `

	for _, _ = range q.Users {
		queryString += `(DEFAULT` +
			`, DEFAULT` +
			`, DEFAULT` +
			`, DEFAULT` +
			`, DEFAULT` +
			`),`
	}

	queryString = queryString[:len(queryString)-1]
	queryString += ` RETURNING
	u."id"
	, u."email"
	, u."full_name"
	, u."is_active"
	, u."created_at"
	, u."updated_at"` // `

	rows, err := c.Query(queryString)
	if err != nil {
		return err
	}
	defer rows.Close()

	i := 0
	for rows.Next() {
		err := rows.Scan(
			&q.Users[i].Id,
			&q.Users[i].Email,
			&q.Users[i].FullName,
			&q.Users[i].IsActive,
			&q.Users[i].CreatedAt,
			&q.Users[i].UpdatedAt,
		)
		if err != nil {
			return err
		}

		i += 1
	}
	return rows.Err()
}
