// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
	"github.com/frk/gosql/testdata/common"
)

type InsertDefaultSingleQuery struct {
	User *common.User3 `rel:"test_user:u"`
	_    gosql.Default `sql:"u.password"`
}
