// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *UpdateFilterSingleQuery) Exec(c gosql.Conn) error {
	var queryString = `UPDATE "test_user" AS u SET (
		"email"
		, "full_name"
		, "is_active"
		, "created_at"
		, "updated_at"
	) = (
		$1
		, $2
		, $3
		, $4
		, $5
	)` // `

	queryString += q.Filter.ToSQL()

	params := []interface{}{
		q.User.Email,
		q.User.FullName,
		q.User.IsActive,
		q.User.CreatedAt,
		q.User.UpdatedAt,
	}
	params = append(params, q.Filter.Params()...)

	_, err := c.Exec(queryString, params...)
	return err
}
