// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *UpdateNullIfSliceQuery) Exec(c gosql.Conn) error {
	var queryString = `UPDATE "test_onconflict" AS k SET (
		"key"
		, "name"
		, "fruit"
		, "value"
	) = (
		x."key"
		, x."name"
		, x."fruit"
		, x."value"
	)
	FROM (VALUES` // `

	params := make([]interface{}, len(q.Data)*5)
	for i, v := range q.Data {
		pos := i * 5

		params[pos+0] = v.Key
		params[pos+1] = v.Name
		params[pos+2] = v.Fruit
		params[pos+3] = v.Value
		params[pos+4] = v.Id

		queryString += `(NULLIF(` + gosql.OrdinalParameters[pos+0] + `, 0)::integer` +
			`, NULLIF(` + gosql.OrdinalParameters[pos+1] + `, '')::text` +
			`, NULLIF(` + gosql.OrdinalParameters[pos+2] + `, '')::text` +
			`, NULLIF(` + gosql.OrdinalParameters[pos+3] + `, 0)::double precision` +
			`, ` + gosql.OrdinalParameters[pos+4] +
			`),`
	}

	queryString = queryString[:len(queryString)-1]
	queryString += ` ) AS x (
		"key"
		, "name"
		, "fruit"
		, "value"
		, "id"
	)
	WHERE k."id" = x."id"::integer` // `

	_, err := c.Exec(queryString, params...)
	return err
}
