// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *UpdatePKeySliceQuery) Exec(c gosql.Conn) error {
	var queryString = `UPDATE "test_user" AS u SET (
		"email"
		, "password"
		, "created_at"
		, "updated_at"
	) = (
		x."email"
		, x."password"
		, x."created_at"
		, x."updated_at"
	)
	FROM (VALUES` // `

	params := make([]interface{}, len(q.Users)*5)
	for i, v := range q.Users {
		pos := i * 5

		params[pos+0] = v.Email
		params[pos+1] = v.Password
		params[pos+2] = v.CreatedAt
		params[pos+3] = v.UpdatedAt
		params[pos+4] = v.Id

		queryString += `(` + gosql.OrdinalParameters[pos+0] + `::text` +
			`, ` + gosql.OrdinalParameters[pos+1] + `::bytea` +
			`, ` + gosql.OrdinalParameters[pos+2] + `::timestamp with time zone` +
			`, ` + gosql.OrdinalParameters[pos+3] + `::timestamp with time zone` +
			`, ` + gosql.OrdinalParameters[pos+4] +
			`),`
	}

	queryString = queryString[:len(queryString)-1]
	queryString += ` ) AS x (
		"email"
		, "password"
		, "created_at"
		, "updated_at"
		, "id"
	)
	WHERE u."id" = x."id"::integer` // `

	_, err := c.Exec(queryString, params...)
	return err
}
