// DO NOT EDIT. This file was generated by github.com/frk/gosql.

package testdata

import (
	"github.com/frk/gosql"
)

func (q *DeleteWithWhereBlock1Query) Exec(c gosql.Conn) error {
	const queryString = `DELETE FROM "test_user"
	WHERE "id" = $1` // `

	_, err := c.Exec(queryString, q.Where.Id)
	return err
}
