// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *DeleteWithUsingJoinBlock1Query) Exec(c gosql.Conn) error {
	const queryString = `DELETE FROM "test_user" AS u
	USING "test_post" AS p
	WHERE u."id" = p."user_id" AND p."is_spam"` // `

	_, err := c.Exec(queryString)
	return err
}
