// DO NOT EDIT. This file was generated by github.com/frk/gosql.

package testdata

import (
	"github.com/frk/gosql"
)

func (q *DeleteWithAllDirectiveQuery) Exec(c gosql.Conn) error {
	const queryString = `DELETE FROM "test_user"` // `

	_, err := c.Exec(queryString)
	return err
}
