// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"context"

	"github.com/frk/gosql"
)

func (q *SelectCountWithFilterQuery) Exec(ctx context.Context, c gosql.Conn) error {
	var queryString = `SELECT COUNT(*) FROM "test_user" AS u
	` // `

	filterString, params := q.Filter.ToSQL(0)
	queryString += filterString

	row := c.QueryRowContext(ctx, queryString, params...)
	return row.Scan(&q.Count)
}
