// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *SelectCountWithWhereBlockQuery) Exec(c gosql.Conn) error {
	const queryString = `SELECT COUNT(*) FROM "test_user" AS u
	WHERE u."full_name" LIKE $1` // `

	row := c.QueryRow(queryString, q.Where.FullName)
	return row.Scan(&q.Count)
}
