// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *SelectCountQuery) Exec(c gosql.Conn) error {
	const queryString = `SELECT COUNT(*) FROM "test_user" AS u
	` // `

	row := c.QueryRow(queryString)
	return row.Scan(&q.Count)
}
