// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *SelectNotExistsWithWhereBlockQuery) Exec(c gosql.Conn) error {
	const queryString = `SELECT NOT EXISTS(SELECT 1 FROM "test_user" AS u
	WHERE lower(u."email") = lower($1)
	LIMIT 1)` // `

	row := c.QueryRow(queryString, q.Where.Email)
	return row.Scan(&q.NotExists)
}
