// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
	"github.com/frk/gosql/internal/testdata"
)

func (q *SelectWithWhereBlockSingle2Query) Exec(c gosql.Conn) error {
	const queryString = `SELECT
	COALESCE("color_text", ''::text)
	, "color_enum"
	, "some_time"
	FROM "column_tests_3"
	WHERE "some_time" < $1
	LIMIT 1` // `

	row := c.QueryRow(queryString, q.Where.SomeTime)

	q.Rel = new(testdata.CT3b)
	return row.Scan(
		&q.Rel.ColorText,
		&q.Rel.ColorEnum,
		&q.Rel.SomeTime,
	)
}
