package main

import (
	"bytes"
	"log"
	"strconv"

	GO "github.com/frk/gosql/internal/golang"
	SQL "github.com/frk/gosql/internal/sqlang"
)

const (
	filepreamble = ` DO NOT EDIT. This file was generated by "github.com/frk/gosql".`
	gosqlimport  = `github.com/frk/gosql`
)

var (
	idblank             = GO.Ident{"_"}
	idrecv              = GO.Ident{"q"}
	idconn              = GO.Ident{"c"}
	ididx               = GO.Ident{"i"}
	iderr               = GO.Ident{"err"}
	idnew               = GO.Ident{"new"}
	idnil               = GO.Ident{"nil"}
	idlen               = GO.Ident{"len"}
	idi64               = GO.Ident{"i64"}
	idres               = GO.Ident{"res"}
	idrow               = GO.Ident{"row"}
	idmake              = GO.Ident{"make"}
	idrows              = GO.Ident{"rows"}
	idexec              = GO.Ident{"Exec"}
	iderror             = GO.Ident{"error"}
	idparams            = GO.Ident{"params"}
	idafterscan         = GO.Ident{"AfterScan"}
	idquery             = GO.Ident{"queryString"}
	idiface             = GO.Ident{"interface{}"}
	idifaces            = GO.Ident{"[]interface{}"}
	idordinals          = GO.QualifiedIdent{"gosql", "OrdinalParameters"}
	sxconn              = GO.QualifiedIdent{"gosql", "Conn"}
	sxerrorinfo         = GO.QualifiedIdent{"gosql", "ErrorInfo"}
	sxexec              = GO.QualifiedIdent{"c", "Exec"}
	sxquery             = GO.QualifiedIdent{"c", "Query"}
	sxqueryrow          = GO.QualifiedIdent{"c", "QueryRow"}
	sxrowscan           = GO.QualifiedIdent{"row", "Scan"}
	sxrowsscan          = GO.QualifiedIdent{"rows", "Scan"}
	sxrowsclose         = GO.QualifiedIdent{"rows", "Close"}
	callrowserr         = GO.CallExpr{Fun: GO.QualifiedIdent{"rows", "Err"}}
	callrowsnext        = GO.CallExpr{Fun: GO.QualifiedIdent{"rows", "Next"}}
	callresrowsaffected = GO.CallExpr{Fun: GO.QualifiedIdent{"res", "RowsAffected"}}
	callinvaluelist     = GO.CallExpr{Fun: GO.QualifiedIdent{"gosql", "InValueList"}}
	calljson            = GO.CallExpr{Fun: GO.QualifiedIdent{"gosql", "JSON"}}
	callmakeparams      = GO.CallExpr{Fun: GO.Ident{"make"}, Args: GO.ArgsList{List: idifaces}}
)

// targetInfo holds the information for the analyzed and db-checked target type.
type targetInfo struct {
	query     *queryStruct
	filter    *filterStruct
	dataField *dataField
	info      *pginfo
}

// skipwrite is a helper method that reports whether or not the field's column should be written to.
func (ti *targetInfo) skipwrite(fc *fieldcolumn) bool {
	return fc.field.readOnly && (ti.query.forceList == nil ||
		(ti.query.forceList.all == false && !ti.query.forceList.contains(fc.colId)))
}

// skipread is a helper method that reports whether or not the field's column should be read from.
func (ti *targetInfo) skipread(fc *fieldcolumn) bool {
	return fc.field.writeOnly && (ti.query.forceList == nil ||
		(ti.query.forceList.all == false && !ti.query.forceList.contains(fc.colId)))
}

// usedefault is a helper method that reports whether or not the SQL's DEFAULT
// marker should be used to write a column.
func (ti *targetInfo) usedefault(fc *fieldcolumn) bool {
	return fc.field.useDefault || (ti.query.defaultList != nil &&
		(ti.query.defaultList.all || ti.query.defaultList.contains(fc.colId)))
}

// skipinit is a helper method that reports whether or not the GO output
// fields should be, if they are pointers, initialized.
func (ti *targetInfo) skipinit() bool {
	return (ti.query.kind == queryKindInsert || ti.query.kind == queryKindUpdate) && // has input fields?
		(ti.query.resultField == nil) // scan output into input fields?
}

func generate(pkgName string, infos []*targetInfo) (*bytes.Buffer, error) {
	g := &generator{infos: infos}
	if err := g.run(pkgName); err != nil {
		return nil, err
	}
	return &g.buf, nil
}

type generator struct {
	infos   []*targetInfo
	pkgName string
	buf     bytes.Buffer

	file GO.File

	// file specific state
	imports GO.ImportDecl

	// query specific state, needs to be reset on each iteration
	nparam     int               // number of parameters
	asvar      bool              // if true, the query string should be declared as a var, not const.
	fclose     bool              // if true, the SQL query needs to be closed (with right parentheses) after the filter's been added.
	insx       []GO.SelectorExpr // slice fields for IN clauses
	queryargs  []GO.ExprNode     // list of arguments to be passed to the query (Exec|Query|QueryRow)
	scanargs   []GO.ExprNode     // list of arguments to be passed to the Scan method
	argroot    GO.ExprNode       // the root node for the fields to be passed as arguments to the query
	scanroot   GO.ExprNode       // the root node for the fields to be scanned
	scaninits  GO.StmtList       // list of pointer initializations for scanning nested fields
	lofallback GO.StmtList

	outputcolumns SQL.ValueExprList //
	sqltailnode   SQL.Node          //
	// scantoinput indicates that the output of the query should be scanned
	// into the input of the query, which in an insert or update is already
	// allocated and therefore needs no initialization.
	scantoinput bool

	sqlInputColumns  SQL.NameGroup
	sqlInputColumns2 SQL.NameGroup
	sqlInputValues   SQL.ValueExprList //
	sqlInputValues2  SQL.ValueExprList //
	targetInfo       *targetInfo
}

func (g *generator) run(pkgName string) error {
	g.imports.Specs = []GO.ImportSpec{{Path: gosqlimport}}

	for _, ti := range g.infos {
		g.nparam = 0
		g.asvar = false
		g.fclose = false
		g.insx = nil
		g.queryargs = nil
		g.scanargs = nil
		g.argroot = nil
		g.scanroot = nil
		g.scaninits = nil
		g.lofallback = nil
		g.outputcolumns = nil
		g.sqltailnode = nil
		g.scantoinput = false

		g.sqlInputColumns = nil
		g.sqlInputColumns2 = nil
		g.sqlInputValues = nil
		g.sqlInputValues2 = nil
		g.targetInfo = ti

		execdecl := g.buildexecdecl(ti)
		g.file.Decls = append(g.file.Decls, execdecl)
	}

	g.file.PkgName = pkgName
	g.file.Preamble = GO.LineComment{filepreamble}
	g.file.Imports = []GO.ImportDeclNode{g.imports}

	return GO.Write(g.file, &g.buf)
}

func (g *generator) buildexecdecl(si *targetInfo) (m GO.MethodDecl) {
	m.Name = idexec
	m.Recv.Name = idrecv
	m.Recv.Type = GO.PointerRecvType{si.query.name}
	m.Type.Params = GO.ParamList{{Names: idconn, Type: sxconn}}
	m.Type.Results = GO.ParamList{{Type: iderror}}

	g.scantoinput = ((si.query.kind == queryKindInsert || si.query.kind == queryKindUpdate) &&
		si.query.dataField.data.isSlice && si.query.resultField == nil)

	g.prepareInput(si)
	g.prepareOutput(si)

	g.prepareGOLimitOffsetFallback(si)

	m.Body.Add(g.buildquerystring(si))
	m.Body.Add(g.buildGOFilterParams(si))

	if len(g.lofallback) > 0 {
		m.Body.Add(g.lofallback)
	}

	m.Body.Add(g.queryexec(si))
	m.Body.Add(g.returnstmt(si))
	return m
}

// prepareInput
func (g *generator) prepareInput(si *targetInfo) {
	// prepare input for the INSERT / UPDATE query
	if len(si.info.input) > 0 {
		g.prepareGOInputFields(si)
		g.prepareSQLInputColumns(si)
	}

	// prepare input for the WHERE clause
	if si.query.whereBlock != nil && len(si.query.whereBlock.items) > 0 {
		sx := GO.SelectorExpr{X: idrecv, Sel: GO.Ident{si.query.whereBlock.name}}
		g.prepareGOInputWhereFields(si.query.whereBlock.items, sx)
	} else if si.query.kind == queryKindUpdate && (si.query.all == false && si.query.filterField == "") {
		g.prepareGOInputPrimaryKeyFields(si)
	}

	// prepare input for the LIMIT clause
	if si.query.limitField != nil && len(si.query.limitField.name) > 0 {
		sx := GO.SelectorExpr{X: idrecv, Sel: GO.Ident{si.query.limitField.name}}
		g.queryargs = append(g.queryargs, sx)
	}

	// prepare input for the OFFSET clause
	if si.query.offsetField != nil && len(si.query.offsetField.name) > 0 {
		sx := GO.SelectorExpr{X: idrecv, Sel: GO.Ident{si.query.offsetField.name}}
		g.queryargs = append(g.queryargs, sx)
	}
}

// prepareGOInputFields prepares a list of GO field selector expressions
// that will be passed as arguments to the query executing function.
func (g *generator) prepareGOInputFields(si *targetInfo) {
	data := si.query.dataField.data
	name := si.query.dataField.name

	// the root node for the fields to be stored
	g.argroot = GO.ExprNode(GO.SelectorExpr{X: idrecv, Sel: GO.Ident{name}})
	if data.isSlice {
		g.argroot = GO.Ident{"v"}
	}

	for _, item := range si.info.input {
		if si.skipwrite(item) { // read only?
			continue
		}
		if si.usedefault(item) { // DEFAULT?
			continue
		}

		// the GO field to be passed as argument
		fx := g.argroot
		for _, node := range item.field.path {
			fx = GO.SelectorExpr{X: fx, Sel: GO.Ident{node.name}}
		}
		fx = GO.SelectorExpr{X: fx, Sel: GO.Ident{item.field.name}}
		fx = g.transformGOInputFieldExpr(fx, item)
		g.queryargs = append(g.queryargs, fx)
	}
}

// transformGOInputFieldExpr ...
func (g *generator) transformGOInputFieldExpr(x GO.ExprNode, fc *fieldcolumn) GO.ExprNode {
	if fc.field.useJSON {
		call := calljson
		call.Args = GO.ArgsList{List: x}
		return call
	}
	return x
}

// prepareSQLInputColumns prepares the target columns for an INSERT or UPDATE
// query, including a list of the SQL parameter placeholders or values.
func (g *generator) prepareSQLInputColumns(si *targetInfo) {
	updateWithSlice := (si.query.kind == queryKindUpdate && si.query.dataField.data.isSlice)

	for _, item := range si.info.input {
		if si.skipwrite(item) { // read only?
			continue
		}

		// the target column
		g.sqlInputColumns = append(g.sqlInputColumns, SQL.Name(item.column.name))

		if si.usedefault(item) {
			g.sqlInputValues = append(g.sqlInputValues, SQL.DEFAULT)
			continue
		}

		if updateWithSlice {
			var col SQL.ColumnIdent
			col.Name = SQL.Name(item.column.name)
			col.Qual = "x"

			var cast SQL.CastExpr
			cast.Expr = col
			cast.Type = item.column.typ.name
			g.sqlInputValues = append(g.sqlInputValues, cast)
			continue
		}

		// the parameter placeholder
		item.sqlparam = g.sqlparam()
		g.sqlInputValues = append(g.sqlInputValues, item.sqlparam)
	}

	if updateWithSlice {
		for _, item := range si.info.pkeys {
			// TODO documentation
			if !si.skipwrite(item) { // read only?
				continue
			}
			g.sqlInputColumns2 = append(g.sqlInputColumns2, SQL.Name(item.column.name))

			item.sqlparam = g.sqlparam()
			g.sqlInputValues2 = append(g.sqlInputValues2, item.sqlparam)
		}
	}
}

// prepareGOInputWhereFields prepares the input for a WHERE clause which is a list of
// the GO "where block" fields that will be passed to the query executing function.
func (g *generator) prepareGOInputWhereFields(items []*predicateItem, sx GO.SelectorExpr) {
	for _, item := range items {
		switch pred := item.pred.(type) {
		case *predicateNested:
			g.prepareGOInputWhereFields(pred.items, GO.SelectorExpr{X: sx, Sel: GO.Ident{pred.name}})
			continue
		case *predicateBetween:
			if x, ok := pred.x.(*fieldDatum); ok {
				sx := GO.SelectorExpr{X: sx, Sel: GO.Ident{pred.name}}
				sx = GO.SelectorExpr{X: sx, Sel: GO.Ident{x.name}}
				g.queryargs = append(g.queryargs, sx)
			}
			if y, ok := pred.y.(*fieldDatum); ok {
				sx := GO.SelectorExpr{X: sx, Sel: GO.Ident{pred.name}}
				sx = GO.SelectorExpr{X: sx, Sel: GO.Ident{y.name}}
				g.queryargs = append(g.queryargs, sx)
			}
		case *predicateField:
			if pred.kind != isIn && pred.kind != notIn {
				var x GO.ExprNode

				x = GO.SelectorExpr{X: sx, Sel: GO.Ident{pred.name}}
				if pred.qua > 0 {

					gotyp := pred.typ.string(true)
					coltyp := g.targetInfo.info.colmap[pred].typ.namefmt + "[]"
					sel, ok := gotyp2coltyp2converter[gotyp][coltyp]
					if !ok {
						// TODO should not happen here, this should be caught while scanning the db
						log.Fatalf("unsupported type conversion: %s - %s", gotyp, coltyp)
					}
					x = GO.CallExpr{Fun: sel, Args: GO.ArgsList{List: x}}
				}

				g.queryargs = append(g.queryargs, x)
			}
		case *predicateColumn:
			// nothing to do
		}
	}
}

// prepareGOInputPrimaryKeyFields prepares the input for a WHERE clause
// using the primary key(s) of the data type.
func (g *generator) prepareGOInputPrimaryKeyFields(si *targetInfo) {
	for _, item := range si.info.pkeys {
		if !si.skipwrite(item) {
			continue
		}

		fx := GO.ExprNode(g.argroot)
		for _, node := range item.field.path {
			fx = GO.SelectorExpr{X: fx, Sel: GO.Ident{node.name}}
		}
		fx = GO.SelectorExpr{X: fx, Sel: GO.Ident{item.field.name}}
		g.queryargs = append(g.queryargs, fx)
	}
}

// prepareGOLimitOffsetFallback
func (g *generator) prepareGOLimitOffsetFallback(si *targetInfo) {
	if field := si.query.limitField; field != nil && field.value > 0 && len(field.name) > 0 {
		sx := GO.SelectorExpr{X: idrecv, Sel: GO.Ident{field.name}}

		asn := GO.AssignStmt{Token: GO.Assign}
		asn.Lhs = sx
		asn.Rhs = GO.IntLit(field.value)

		ifzero := GO.IfStmt{}
		ifzero.Cond = GO.BinaryExpr{X: sx, Op: GO.BinaryEql, Y: GO.IntLit(0)}
		ifzero.Body = GO.BlockStmt{List: []GO.StmtNode{asn}}
		g.lofallback = append(g.lofallback, ifzero)
	}

	if field := si.query.offsetField; field != nil && field.value > 0 && len(field.name) > 0 {
		sx := GO.SelectorExpr{X: idrecv, Sel: GO.Ident{field.name}}

		asn := GO.AssignStmt{Token: GO.Assign}
		asn.Lhs = sx
		asn.Rhs = GO.IntLit(field.value)

		ifzero := GO.IfStmt{}
		ifzero.Cond = GO.BinaryExpr{X: sx, Op: GO.BinaryEql, Y: GO.IntLit(0)}
		ifzero.Body = GO.BlockStmt{List: []GO.StmtNode{asn}}
		g.lofallback = append(g.lofallback, ifzero)
	}

	if len(g.lofallback) > 0 {
		g.lofallback = append(g.lofallback, GO.NL{})
	}
}

// prepareOutput .................
func (g *generator) prepareOutput(si *targetInfo) {
	if len(si.info.output) > 0 {
		skipinit := si.skipinit()
		g.prepareOutputGORoot(si, skipinit)
		g.prepareOutputGORootFields(si, skipinit)
		g.prepareOutputSQLColumns(si)
	}
}

// prepareOutputGORoot resolves the GO root expression of the fields into which
// the output will be scanned, additionally if the root needs to be initialized
// before scanning, an initialization statement will be prepared as well.
func (g *generator) prepareOutputGORoot(si *targetInfo, skipinit bool) {
	data := si.query.dataField.data
	name := si.query.dataField.name
	if si.query.resultField != nil {
		data = si.query.resultField.data
		name = si.query.resultField.name
	}

	g.scanroot = GO.ExprNode(GO.SelectorExpr{X: idrecv, Sel: GO.Ident{name}})
	if data.isSlice && skipinit {
		g.scanroot = GO.IndexExpr{X: g.scanroot, Index: GO.Ident{"i"}}
	} else if data.isSlice || data.isIter {
		g.scanroot = GO.Ident{"v"}
	}

	if !skipinit {
		// build the initialization statement for the g.scanroot node
		var rootinit GO.StmtNode
		if !data.isSlice && !data.isIter && data.isPointer {
			g.scaninits = append(g.scaninits, GO.NL{})

			init := GO.AssignStmt{Token: GO.Assign}
			init.Lhs, init.Rhs = g.scanroot, GO.CallNewExpr{g.rectype(data)}
			rootinit = init
		} else if (data.isSlice || data.isIter) && data.isPointer {
			init := GO.AssignStmt{Token: GO.AssignDefine}
			init.Lhs, init.Rhs = g.scanroot, GO.CallNewExpr{g.rectype(data)}
			rootinit = init
		} else if (data.isSlice || data.isIter) && !data.isPointer {
			init := GO.VarDecl{}
			init.Spec = GO.ValueSpec{Names: GO.Ident{"v"}, Type: g.rectype(data)}
			rootinit = GO.DeclStmt{init}
		}
		if rootinit != nil {
			g.scaninits = append(g.scaninits, rootinit)
		}
	}
}

// prepareOutputGORootFields ....
func (g *generator) prepareOutputGORootFields(si *targetInfo, skipinit bool) {
	// done is used to keep track of pointer fields whose
	// initialization statements have already been created
	var done = make(map[string]bool)

	for _, item := range si.info.output {
		if si.skipread(item) { // writeonly?
			continue
		}

		key := "" // key for the done map

		fx := g.scanroot
		for _, node := range item.field.path {
			fx = GO.SelectorExpr{X: fx, Sel: GO.Ident{node.name}}

			if skipinit {
				continue
			}

			key += node.name
			if node.isPointer && !done[key] {
				if node.isImported {
					g.addimport(node.typePkgPath, node.typePkgName, node.typePkgLocal)
				}

				// nested pointer field initialization statement
				init := GO.AssignStmt{Token: GO.Assign}
				init.Lhs, init.Rhs = fx, GO.CallNewExpr{g.pathelemtype(node)}
				g.scaninits = append(g.scaninits, init)

				done[key] = true
			}
		}

		fx = GO.SelectorExpr{X: fx, Sel: GO.Ident{item.field.name}}
		fx = GO.UnaryExpr{Op: GO.UnaryAmp, X: fx}
		fx = g.transformOutputGOFieldExpr(fx, item)
		g.scanargs = append(g.scanargs, fx)
	}
}

// transformOutputGOFieldExpr ...
func (g *generator) transformOutputGOFieldExpr(x GO.ExprNode, fc *fieldcolumn) GO.ExprNode {
	if fc.field.useJSON {
		call := calljson
		call.Args = GO.ArgsList{List: x}
		return call
	}
	return x
}

// prepareOutputSQLColumns prepares the list of SQL columns to be returned by the query.
func (g *generator) prepareOutputSQLColumns(si *targetInfo) {
	for _, item := range si.info.output {
		if si.skipread(item) { // writeonly?
			continue
		}

		// TODO(mkopriva):
		// - check whether or not the column can be NULL and if so add a COALESCE
		// - check whether or not the field has the "usecoalesce" flag set to true and if so add a COALESCE
		// - ... anything else?
		g.outputcolumns = append(g.outputcolumns, g.sqlcolref(item.colId))
	}
}

func (g *generator) buildquerystring(si *targetInfo) (stmt GO.StmtNode) {

	sqlnode := g.sqlnode(si)

	var decl GO.DeclNode
	if g.declarevar(si) {
		decl = GO.VarDecl{Spec: GO.ValueSpec{
			Names:   idquery,
			Values:  GO.RawStringNode{N: sqlnode},
			Comment: GO.LineComment{" `"},
		}}
	} else {
		decl = GO.ConstDecl{Spec: GO.ValueSpec{
			Names:   idquery,
			Values:  GO.RawStringNode{N: sqlnode},
			Comment: GO.LineComment{" `"},
		}}
	}

	if (si.query.kind == queryKindInsert || si.query.kind == queryKindUpdate) && si.query.dataField.data.isSlice {
		result := GO.StmtList{GO.DeclStmt{decl}, GO.NL{}}

		idrel := GO.QualifiedIdent{idrecv.Name, si.query.dataField.name}
		numfields := GO.IntLit(len(g.queryargs))

		if len(g.queryargs) > 0 {
			// params := make([]interface{}, len(q.T)*numoffields)
			asn := GO.AssignStmt{Token: GO.AssignDefine}
			asn.Lhs = idparams
			asn.Rhs = GO.CallMakeExpr{
				Type: idifaces,
				Size: GO.BinaryExpr{
					Op: GO.BinaryMul,
					X:  GO.CallLenExpr{idrel},
					Y:  numfields,
				},
			}
			result = append(result, asn)
		}

		// for i, v := range q.DataSlice {
		loop := GO.ForStmt{}
		{
			if len(g.queryargs) > 0 {
				// for i, v := range q.DataSlice {
				rangeclause := GO.ForRangeClause{}
				rangeclause.Key = GO.Ident{"i"}
				rangeclause.Value = GO.Ident{"v"}
				rangeclause.X = idrel
				rangeclause.Define = true
				loop.Clause = rangeclause

				// pos := i * 4
				asn2 := GO.AssignStmt{Token: GO.AssignDefine}
				asn2.Lhs = GO.Ident{"pos"}
				asn2.Rhs = GO.BinaryExpr{Op: GO.BinaryMul, X: GO.Ident{"i"}, Y: numfields}
				loop.Body = GO.BlockStmt{List: []GO.StmtNode{asn2, GO.NL{}}}

				// params[pos+123] = v.SomeField
				assigns := make([]GO.StmtNode, len(g.queryargs))
				for i, item := range g.queryargs {
					indx := GO.BinaryExpr{Op: GO.BinaryAdd, X: GO.Ident{"pos"}, Y: GO.IntLit(i)}
					asn3 := GO.AssignStmt{Token: GO.Assign}
					asn3.Lhs = GO.IndexExpr{X: idparams, Index: indx}
					asn3.Rhs = item
					assigns[i] = asn3
				}
				loop.Body.List = append(loop.Body.List, assigns...)
				loop.Body.List = append(loop.Body.List, GO.NL{})
			} else {
				// for _, _ := range q.DataSlice {
				rangeclause := GO.ForRangeClause{}
				rangeclause.Key = GO.Ident{"_"}
				rangeclause.Value = GO.Ident{"_"}
				rangeclause.X = idrel
				loop.Clause = rangeclause
			}

			////////////////////////////////////////////////////////
			numdefs := 0
			numvals := len(g.sqlInputValues) + len(g.sqlInputValues2)
			concats := make([]GO.ExprNode, numvals+1) // +1 for the final `),`
			for i, item := range append(g.sqlInputValues, g.sqlInputValues2...) {
				sep := `, `
				if i == 0 {
					sep = `(`
				}

				if item == SQL.DEFAULT {
					numdefs += 1
					concats[i] = GO.RawStringLit(sep + `DEFAULT`)
				} else {
					idxexpr := GO.BinaryExpr{Op: GO.BinaryAdd,
						X: GO.Ident{"pos"}, Y: GO.IntLit(i - numdefs),
					}

					// `, ` + gosql.OrdinalParameters[pos+2] +
					concat := GO.BinaryExpr{Op: GO.BinaryAdd}
					concat.X = GO.RawStringLit(sep)
					concat.Y = GO.IndexExpr{X: idordinals, Index: idxexpr}
					concats[i] = concat
				}
			}

			concats[len(concats)-1] = GO.RawStringLit(`),`)

			asn4 := GO.AssignStmt{Token: GO.AssignAdd}
			asn4.Lhs = idquery
			asn4.Rhs = GO.MultiLineExpr{Op: GO.BinaryAdd, Exprs: concats}

			loop.Body.List = append(loop.Body.List, asn4)
		}
		result = append(result, loop)

		asn5 := GO.AssignStmt{Token: GO.Assign}
		asn5.Lhs = idquery
		asn5.Rhs = GO.SliceExpr{X: idquery,
			High: GO.BinaryExpr{Op: GO.BinarySub, X: GO.CallLenExpr{idquery}, Y: GO.IntLit(1)},
		}
		result = append(result, GO.NL{}, asn5)

		if g.sqltailnode != nil {
			asn6 := GO.AssignStmt{Token: GO.AssignAdd}
			asn6.Lhs = idquery
			asn6.Rhs = GO.RawStringNode{Prefix: " ", N: g.sqltailnode, Comment: &GO.LineComment{" `"}}
			result = append(result, asn6)
		}
		return result

	} else if len(g.insx) > 0 {
		// prepare the var declarations
		vardecl := GO.VarDecl{}

		nstatic := GO.ValueSpec{}
		nstatic.Names = GO.Ident{"nstatic"}
		nstatic.Values = GO.IntLit(g.nparam)
		nstatic.Comment = GO.LineComment{" number of static parameters"}

		specs := GO.ValueSpecList{nstatic}
		for i, sx := range g.insx {
			num := strconv.Itoa(i + 1)

			lenspec := GO.ValueSpec{}
			lenspec.Names = GO.Ident{"len" + num}
			lenspec.Values = GO.CallExpr{Fun: idlen, Args: GO.ArgsList{List: sx}}
			lenspec.Comment = GO.LineComment{" length of slice #" + num + " to be unnested"}

			posspec := GO.ValueSpec{}
			posspec.Names = GO.Ident{"pos" + num}
			if i == 0 {
				// the first position is set to the value of nstatic
				posspec.Values = GO.Ident{"nstatic"}
			} else {
				// the rest of the positions are calculated from
				// adding the previous length to the previous position
				prev := strconv.Itoa(i)
				prevlen, prevpos := GO.Ident{"len" + prev}, GO.Ident{"pos" + prev}
				posspec.Values = GO.BinaryExpr{X: prevpos, Op: GO.BinaryAdd, Y: prevlen}
			}
			posspec.Comment = GO.LineComment{" starting position of slice #" + num + " parameters"}

			specs = append(specs, lenspec, posspec)
		}
		vardecl.Spec = specs

		// next is the query declaration
		list := GO.StmtList{GO.DeclStmt{vardecl}, GO.NL{}, GO.DeclStmt{decl}, GO.NL{}}

		// define the params variable
		asn := GO.AssignStmt{Token: GO.AssignDefine}
		asn.Lhs = idparams
		callmake := callmakeparams
		bin := GO.BinaryExpr{X: GO.Ident{"nstatic"}, Op: GO.BinaryAdd, Y: GO.Ident{"len1"}}
		for i := 1; i < len(g.insx); i++ {
			y := GO.Ident{"len" + strconv.Itoa(i+1)}
			bin = GO.BinaryExpr{X: bin, Op: GO.BinaryAdd, Y: y}
		}
		callmake.Args.AddExprs(bin)
		asn.Rhs = callmake
		list = append(list, asn)

		// directly assign non-slice params
		for i, arg := range g.queryargs {
			asn := GO.AssignStmt{Token: GO.Assign}
			asn.Lhs = GO.IndexExpr{X: idparams, Index: GO.IntLit(i)}
			asn.Rhs = arg
			list = append(list, asn)
		}

		for i, sx := range g.insx {
			lenid := GO.Ident{"len" + strconv.Itoa(i+1)}
			posid := GO.Ident{"pos" + strconv.Itoa(i+1)}

			forclause := GO.ForClause{}
			forclause.Init = GO.AssignStmt{Token: GO.AssignDefine, Lhs: ididx, Rhs: GO.IntLit(0)}
			forclause.Cond = GO.BinaryExpr{X: ididx, Op: GO.BinaryLss, Y: lenid}
			forclause.Post = GO.IncDecStmt{X: ididx, Token: GO.IncDecIncrement}
			loop := GO.ForStmt{Clause: forclause}

			asn := GO.AssignStmt{Token: GO.Assign}
			asn.Lhs = GO.IndexExpr{X: idparams, Index: GO.BinaryExpr{X: posid, Op: GO.BinaryAdd, Y: ididx}}
			asn.Rhs = GO.IndexExpr{X: sx, Index: ididx}

			loop.Body = GO.BlockStmt{List: []GO.StmtNode{asn}}

			list = append(list, loop)
		}

		return append(list, GO.NL{})
	} else if len(si.query.filterField) > 0 {
		list := GO.StmtList{GO.DeclStmt{decl}, GO.NL{}}

		// q.Filter.ToSQL()
		stmt := GO.AssignStmt{Token: GO.AssignAdd}
		stmt.Lhs = idquery
		stmt.Rhs = GO.CallExpr{Fun: GO.SelectorExpr{
			X:   GO.SelectorExpr{X: idrecv, Sel: GO.Ident{si.query.filterField}},
			Sel: GO.Ident{"ToSQL"},
		}}
		list = append(list, stmt)

		if g.sqltailnode != nil {
			stmt := GO.AssignStmt{Token: GO.AssignAdd}
			stmt.Lhs = idquery
			stmt.Rhs = GO.RawStringNode{Prefix: " ", N: g.sqltailnode, Comment: &GO.LineComment{" `"}}
			list = append(list, stmt)
		}
		if g.fclose {
			stmt := GO.AssignStmt{Token: GO.AssignAdd}
			stmt.Lhs = idquery
			stmt.Rhs = GO.RawStringLit(`)`)
			list = append(list, stmt)
		}
		list = append(list, GO.NL{})
		return list
	}
	return GO.StmtList{GO.DeclStmt{decl}, GO.NL{}}
}

func (g *generator) buildGOFilterParams(si *targetInfo) (stmt GO.StmtNode) {
	if len(si.query.filterField) > 0 {
		var list GO.StmtList

		// q.Filter.Params()
		call := GO.CallExpr{Fun: GO.SelectorExpr{
			X:   GO.SelectorExpr{X: idrecv, Sel: GO.Ident{si.query.filterField}},
			Sel: GO.Ident{"Params"},
		}}

		if si.query.kind == queryKindUpdate {
			var stmt1 GO.AssignStmt
			stmt1.Token = GO.AssignDefine
			stmt1.Lhs = idparams
			stmt1.Rhs = GO.SliceLit{
				Type:  idifaces,
				Elems: GO.ExprList(g.queryargs),
			}

			var stmt2 GO.AssignStmt
			stmt2.Token = GO.Assign
			stmt2.Lhs = idparams
			stmt2.Rhs = GO.CallExpr{Fun: GO.Ident{"append"}, Args: GO.ArgsList{
				List:     GO.ExprList{idparams, call},
				Ellipsis: true,
			}}
			list = append(list, stmt1, stmt2, GO.NL{})
		} else {
			var stmt GO.AssignStmt
			stmt.Token = GO.AssignDefine
			stmt.Lhs = idparams
			stmt.Rhs = call
			list = append(list, stmt)
		}
		return list
	}
	return GO.NoOp{}
}

func (g *generator) queryexec(si *targetInfo) (stmt GO.StmtNode) {
	args := GO.ArgsList{List: idquery}
	if len(g.insx) > 0 || len(si.query.filterField) > 0 || ((si.query.kind == queryKindInsert || si.query.kind == queryKindUpdate) && si.query.dataField.data.isSlice && len(g.queryargs) > 0) {
		args.AddExprs(idparams)
		args.Ellipsis = true
	} else {
		args.AddExprs(g.queryargs...)
		if args.Len() > 3 {
			args.OnePerLine = 2
		}
	}

	// produce c.Exec( ... ) call
	{
		if !si.query.kind.isSelect() && si.query.returnList == nil && si.query.resultField == nil {

			if rafield := si.query.rowsAffectedField; rafield != nil {
				// call exec & assign res, err
				asn := GO.AssignStmt{Token: GO.AssignDefine}
				asn.Lhs = GO.ExprList{idres, iderr}
				asn.Rhs = GO.CallExpr{Fun: sxexec, Args: args}

				// check err
				iferr := GO.IfStmt{}
				iferr.Cond = GO.BinaryExpr{X: iderr, Op: GO.BinaryNeq, Y: idnil}
				iferr.Body = GO.BlockStmt{List: []GO.StmtNode{g.returnerr(si, iderr)}}

				// call RowsAffected & assing i64, err
				asn2 := GO.AssignStmt{Token: GO.AssignDefine}
				asn2.Lhs = GO.ExprList{idi64, iderr}
				asn2.Rhs = callresrowsaffected

				// check err
				iferr2 := GO.IfStmt{}
				iferr2.Cond = GO.BinaryExpr{X: iderr, Op: GO.BinaryNeq, Y: idnil}
				iferr2.Body = GO.BlockStmt{List: []GO.StmtNode{g.returnerr(si, iderr)}}

				//
				asn3 := GO.AssignStmt{Token: GO.Assign}
				asn3.Lhs = GO.SelectorExpr{X: idrecv, Sel: GO.Ident{rafield.name}}
				if rafield.kind == kindInt64 {
					asn3.Rhs = idi64
				} else {
					args := GO.ArgsList{List: idi64}
					asn3.Rhs = GO.CallExpr{Fun: GO.Ident{rafield.kind.String()}, Args: args}
				}

				return GO.StmtList{asn, iferr, asn2, iferr2, GO.NL{}, asn3}
			} else {
				asn := GO.AssignStmt{Token: GO.AssignDefine}
				asn.Lhs = GO.ExprList{idblank, iderr}
				asn.Rhs = GO.CallExpr{Fun: sxexec, Args: args}
				return asn
			}
		}
	}

	// produce c.QueryRow( ... ) call
	{
		data := si.query.dataField.data
		if si.query.resultField != nil {
			data = si.query.resultField.data
		}

		if !data.isSlice && !data.isIter {
			asn := GO.AssignStmt{Token: GO.AssignDefine}
			asn.Lhs = idrow
			asn.Rhs = GO.CallExpr{Fun: sxqueryrow, Args: args}
			//return GO.StmtList{asn, GO.NL{}}
			return GO.StmtList{asn}
		}
	}

	// produce c.Query( ... ) call with if-err-check, defer-rows-close, and
	// for-rows-next loop to scan the rows
	{

		asn := GO.AssignStmt{Token: GO.AssignDefine}
		asn.Lhs = GO.ExprList{idrows, iderr}
		asn.Rhs = GO.CallExpr{Fun: sxquery, Args: args}

		iferr := GO.IfStmt{}
		iferr.Cond = GO.BinaryExpr{X: iderr, Op: GO.BinaryNeq, Y: idnil}
		iferr.Body = GO.BlockStmt{List: []GO.StmtNode{g.returnerr(si, iderr)}}

		defclose := GO.DeferStmt{}
		defclose.Call = GO.CallExpr{Fun: sxrowsclose}

		fornext := g.fornext(si, g.scantoinput)
		if g.scantoinput {
			asni := GO.AssignStmt{Token: GO.AssignDefine}
			asni.Lhs = GO.Ident{"i"}
			asni.Rhs = GO.IntLit(0)
			return GO.StmtList{asn, iferr, defclose, GO.NL{}, asni, fornext}
		}
		return GO.StmtList{asn, iferr, defclose, GO.NL{}, fornext}
	}
	return stmt
}

func (g *generator) returnerr(si *targetInfo, errx GO.ExprNode) GO.ReturnStmt {
	if si.query.errorHandlerField == nil {
		return GO.ReturnStmt{errx}
	}
	if si.query.errorHandlerField.isInfo {
		lit := GO.StructLit{Type: sxerrorinfo, Compact: true}
		lit.Elems = []GO.FieldElement{
			{"Error", iderr},
			{"Query", idquery},
			{"SpecKind", GO.StringLit(si.query.kind.String())},
			{"SpecName", GO.StringLit(si.query.name)},
			{"SpecValue", idrecv},
		}
		litptr := GO.UnaryExpr{Op: GO.UnaryAmp, X: lit}

		sx := GO.SelectorExpr{X: idrecv, Sel: GO.Ident{si.query.errorHandlerField.name}}
		fun := GO.SelectorExpr{X: sx, Sel: GO.Ident{"HandleErrorInfo"}}
		call := GO.CallExpr{Fun: fun, Args: GO.ArgsList{List: litptr}}
		return GO.ReturnStmt{call}

		// TODO if errx is not iderr, then errx is probably a CallFunc and
		// should first be executed and it's result passed into HandleErrorInfo..
	}
	sx := GO.SelectorExpr{X: idrecv, Sel: GO.Ident{si.query.errorHandlerField.name}}
	fun := GO.SelectorExpr{X: sx, Sel: GO.Ident{"HandleError"}}
	call := GO.CallExpr{Fun: fun, Args: GO.ArgsList{List: errx}}
	return GO.ReturnStmt{call}
}

func (g *generator) fornext(si *targetInfo, inputscan bool) (stmt GO.ForStmt) {
	stmt.Clause = GO.ForCondition{callrowsnext}
	// scan & assign error
	{
		var args GO.ArgsList
		if len(g.scanargs) > 2 {
			args.OnePerLine = 1
		}
		args.AddExprs(g.scanargs...)
		stmt.Body.List = append(stmt.Body.List, g.scaninits...)

		asn := GO.AssignStmt{Token: GO.AssignDefine}
		asn.Lhs = iderr
		asn.Rhs = GO.CallExpr{Fun: sxrowsscan, Args: args}
		stmt.Body.List = append(stmt.Body.List, asn)
	}

	// check error & newline
	{
		iferr := GO.IfStmt{}
		iferr.Cond = GO.BinaryExpr{X: iderr, Op: GO.BinaryNeq, Y: idnil}
		iferr.Body = GO.BlockStmt{List: []GO.StmtNode{g.returnerr(si, iderr)}}
		stmt.Body.List = append(stmt.Body.List, iferr, GO.NL{})
	}

	// append OR iterate
	{
		data := si.query.dataField.data
		fieldname := si.query.dataField.name
		if si.query.resultField != nil {
			data = si.query.resultField.data
			fieldname = si.query.resultField.name
		}

		if data.isAfterScanner {
			// call afterscan
			sx := GO.SelectorExpr{X: g.scanroot, Sel: idafterscan}
			afterscan := GO.ExprStmt{GO.CallExpr{Fun: sx}}
			stmt.Body.List = append(stmt.Body.List, afterscan)
		}

		if data.isIter {
			var call GO.CallExpr
			if len(data.iterMethod) > 0 {
				call = GO.CallExpr{Fun: GO.SelectorExpr{
					X:   GO.SelectorExpr{X: idrecv, Sel: GO.Ident{fieldname}},
					Sel: GO.Ident{data.iterMethod}},
					Args: GO.ArgsList{List: GO.Ident{"v"}},
				}
			} else {
				call = GO.CallExpr{Fun: GO.SelectorExpr{
					X:   idrecv,
					Sel: GO.Ident{fieldname}},
					Args: GO.ArgsList{List: GO.Ident{"v"}},
				}
			}

			asn := GO.AssignStmt{Token: GO.AssignDefine}
			asn.Lhs = iderr
			asn.Rhs = call

			iferr := GO.IfStmt{}
			iferr.Init = asn
			iferr.Cond = GO.BinaryExpr{X: iderr, Op: GO.BinaryNeq, Y: idnil}
			iferr.Body = GO.BlockStmt{List: []GO.StmtNode{g.returnerr(si, iderr)}}
			stmt.Body.List = append(stmt.Body.List, iferr)
		} else if g.scantoinput {
			asn := GO.AssignStmt{Token: GO.AssignAdd}
			asn.Lhs = GO.Ident{"i"}
			asn.Rhs = GO.IntLit(1)
			stmt.Body.List = append(stmt.Body.List, asn)
		} else {
			appnd := GO.CallExpr{Fun: GO.Ident{"append"}}
			appnd.Args = GO.ArgsList{List: GO.ExprList{
				GO.SelectorExpr{X: idrecv, Sel: GO.Ident{fieldname}},
				GO.Ident{"v"},
			}}

			asn := GO.AssignStmt{Token: GO.Assign}
			asn.Lhs = GO.SelectorExpr{X: idrecv, Sel: GO.Ident{fieldname}}
			asn.Rhs = appnd
			stmt.Body.List = append(stmt.Body.List, asn)
		}
	}
	return stmt
}

func (g *generator) returnstmt(si *targetInfo) (stmt GO.StmtNode) {
	if si.query.rowsAffectedField != nil {
		return GO.ReturnStmt{idnil}
	}
	if si.query.kind.isSelect() || si.query.returnList != nil {
		dataField := si.query.dataField

		// does the record type need pre-allocation? and is it imported?
		if dataField.data.typeInfo.isImported && (dataField.data.isSlice || dataField.data.isPointer) && (si.query.kind != queryKindInsert && si.query.kind != queryKindUpdate) {
			g.addimport(dataField.data.typeInfo.pkgPath, dataField.data.typeInfo.pkgName, dataField.data.typeInfo.pkgLocal)
		}

		if dataField.data.isSlice || dataField.data.isArray || dataField.data.isIter {
			if si.query.errorHandlerField != nil && si.query.errorHandlerField.isInfo {
				asn := GO.AssignStmt{Token: GO.AssignDefine}
				asn.Lhs = iderr
				asn.Rhs = callrowserr

				iferr := GO.IfStmt{}
				iferr.Init = asn
				iferr.Cond = GO.BinaryExpr{X: iderr, Op: GO.BinaryNeq, Y: idnil}
				iferr.Body = GO.BlockStmt{List: []GO.StmtNode{g.returnerr(si, iderr)}}

				return GO.StmtList{iferr, GO.ReturnStmt{idnil}}
			}
			return g.returnerr(si, callrowserr)
		} else {
			var args GO.ArgsList
			var list GO.StmtList // result

			if si.query.kind.isNonFromSelect() {
				fx := GO.SelectorExpr{X: idrecv, Sel: GO.Ident{dataField.name}}
				args.AddExprs(GO.UnaryExpr{Op: GO.UnaryAmp, X: fx})
			} else {
				if len(g.scanargs) > 2 {
					args.OnePerLine = 1
				}
				args.AddExprs(g.scanargs...)
				list = append(list, g.scaninits...)
			}

			if !dataField.data.isAfterScanner {
				call := GO.CallExpr{Fun: sxrowscan, Args: args}
				if si.query.errorHandlerField != nil && si.query.errorHandlerField.isInfo {
					asn := GO.AssignStmt{Token: GO.AssignDefine}
					asn.Lhs = iderr
					asn.Rhs = call

					iferr := GO.IfStmt{}
					iferr.Cond = GO.BinaryExpr{X: iderr, Op: GO.BinaryNeq, Y: idnil}
					iferr.Body = GO.BlockStmt{List: []GO.StmtNode{g.returnerr(si, iderr)}}

					list = append(list, asn, iferr, GO.ReturnStmt{idnil})
				} else {
					list = append(list, g.returnerr(si, call))
				}
			} else {
				// scan & assign error
				asn := GO.AssignStmt{Token: GO.AssignDefine}
				asn.Lhs = iderr
				asn.Rhs = GO.CallExpr{Fun: sxrowscan, Args: args}

				// check error
				iferr := GO.IfStmt{}
				iferr.Cond = GO.BinaryExpr{X: iderr, Op: GO.BinaryNeq, Y: idnil}
				iferr.Body = GO.BlockStmt{List: []GO.StmtNode{g.returnerr(si, iderr)}}

				// call afterscan
				sx := GO.SelectorExpr{X: idrecv, Sel: GO.Ident{dataField.name}}
				sx = GO.SelectorExpr{X: sx, Sel: idafterscan}
				afterscan := GO.ExprStmt{GO.CallExpr{Fun: sx}}

				// call afterscan
				ret := GO.ReturnStmt{idnil}

				// done
				list = append(list, asn, iferr, GO.NL{}, afterscan, ret)
			}

			return list
		}
	}

	// result field
	if si.query.resultField != nil {
		rel := si.query.resultField
		// does the record type need pre-allocation? and is it imported?
		if rel.data.typeInfo.isImported && (rel.data.isSlice || rel.data.isPointer) {
			g.addimport(rel.data.typeInfo.pkgPath, rel.data.typeInfo.pkgName, rel.data.typeInfo.pkgLocal)
		}

		if rel.data.isSlice || rel.data.isArray || rel.data.isIter {
			if si.query.errorHandlerField != nil && si.query.errorHandlerField.isInfo {
				asn := GO.AssignStmt{Token: GO.AssignDefine}
				asn.Lhs = iderr
				asn.Rhs = callrowserr

				iferr := GO.IfStmt{}
				iferr.Init = asn
				iferr.Cond = GO.BinaryExpr{X: iderr, Op: GO.BinaryNeq, Y: idnil}
				iferr.Body = GO.BlockStmt{List: []GO.StmtNode{g.returnerr(si, iderr)}}

				return GO.StmtList{iferr, GO.ReturnStmt{idnil}}
			}
			return g.returnerr(si, callrowserr)
		} else {
			var args GO.ArgsList
			if len(g.scanargs) > 2 {
				args.OnePerLine = 1
			}
			args.AddExprs(g.scanargs...)

			var list GO.StmtList // result
			list = append(list, g.scaninits...)

			if !rel.data.isAfterScanner {
				call := GO.CallExpr{Fun: sxrowscan, Args: args}
				if si.query.errorHandlerField != nil && si.query.errorHandlerField.isInfo {
					asn := GO.AssignStmt{Token: GO.AssignDefine}
					asn.Lhs = iderr
					asn.Rhs = call

					iferr := GO.IfStmt{}
					iferr.Cond = GO.BinaryExpr{X: iderr, Op: GO.BinaryNeq, Y: idnil}
					iferr.Body = GO.BlockStmt{List: []GO.StmtNode{g.returnerr(si, iderr)}}

					list = append(list, asn, iferr, GO.ReturnStmt{idnil})
				} else {
					list = append(list, g.returnerr(si, call))
				}
			} else {
				// scan & assing error
				asn := GO.AssignStmt{Token: GO.AssignDefine}
				asn.Lhs = iderr
				asn.Rhs = GO.CallExpr{Fun: sxrowscan, Args: args}

				// check error
				iferr := GO.IfStmt{}
				iferr.Cond = GO.BinaryExpr{X: iderr, Op: GO.BinaryNeq, Y: idnil}
				iferr.Body = GO.BlockStmt{List: []GO.StmtNode{g.returnerr(si, iderr)}}

				// call afterscan
				sx := GO.SelectorExpr{X: idrecv, Sel: GO.Ident{rel.name}}
				sx = GO.SelectorExpr{X: sx, Sel: idafterscan}
				afterscan := GO.ExprStmt{GO.CallExpr{Fun: sx}}

				// call afterscan
				ret := GO.ReturnStmt{idnil}

				// done
				list = append(list, asn, iferr, GO.NL{}, afterscan, ret)
			}

			return list
		}
	}

	return g.returnerr(si, iderr)
}

func (g *generator) rectype(data dataType) GO.TypeNode {
	if data.typeInfo.isImported {
		return GO.QualifiedIdent{data.typeInfo.pkgName, data.typeInfo.name}
	}
	return GO.Ident{data.typeInfo.name}
}

func (g *generator) pathelemtype(node *fieldNode) GO.TypeNode {
	if node.isImported {
		return GO.QualifiedIdent{node.typePkgName, node.typeName}
	}
	return GO.Ident{node.typeName}
}

func (g *generator) addimport(path, name, local string) {
	// check that the package path hasn't yet been added to the imports
	for _, spec := range g.imports.Specs {
		if string(spec.Path) == path {
			return
		}
	}

	// if the local name is the same as the package name set it to empty
	if local == name {
		local = ""
	}

	spec := GO.ImportSpec{Path: GO.StringLit(path), Name: GO.Ident{local}}
	g.imports.Specs = append(g.imports.Specs, spec)
}

func (g *generator) sqlnode(si *targetInfo) (node GO.Node) {
	switch si.query.kind {
	case queryKindInsert:
		return g.sqlinsert(si)
	case queryKindUpdate:
		return g.sqlupdate(si)
	case queryKindSelect:
		return g.sqlselect(si)
	case queryKindSelectCount:
		return g.sqlselectcount(si)
	case queryKindSelectExists, queryKindSelectNotExists:
		return g.sqlselectexists(si)
	case queryKindDelete:
		return g.sqldelete(si)
	}
	return node
}

// sqlinsert builds and returns an SQL.InsertStatement.
func (g *generator) sqlinsert(si *targetInfo) (stmt SQL.InsertStatement) {
	var src SQL.InsertSource
	if si.query.dataField.data.isSlice {
		src.Values = &SQL.ValuesClause{}
	} else {
		src.Values = &SQL.ValuesClause{g.sqlInputValues}
	}

	stmt.Head.Table = g.sqlrelid(si.query.dataField.relId)
	stmt.Head.Columns = g.sqlInputColumns
	stmt.Head.Overriding = overridingKindToSQLOverridingClause[si.query.overridingKind]
	stmt.Head.Source = src
	//stmt.Head.Source.Select = nil

	if si.query.dataField.data.isSlice && (len(g.outputcolumns) > 0 || si.query.onConflictBlock != nil) {
		var tail SQL.InsertTail
		tail.OnConflict = g.sqlonconflict(si)
		tail.Returning = SQL.ReturningClause(g.outputcolumns)
		g.sqltailnode = tail
	} else {
		stmt.Tail.OnConflict = g.sqlonconflict(si)
		stmt.Tail.Returning = SQL.ReturningClause(g.outputcolumns)
	}
	return stmt
}

func (g *generator) sqlupdate(si *targetInfo) (stmt SQL.UpdateStatement) {
	stmt.Head.Table = g.sqlrelid(si.query.dataField.relId)
	stmt.Head.Set.Targets = g.sqlInputColumns
	stmt.Head.Set.Values.Exprs = g.sqlInputValues
	stmt.Head.From = g.sqlfrom(si.query.joinBlock)

	if si.query.kind == queryKindUpdate && si.query.dataField.data.isSlice {
		// SQL.ValuesListClausePartial{}
		// SQL.ValuesListAliasPartial{}
		stmt.Head.From.List = append(stmt.Head.From.List, SQL.ValuesListClausePartial{})

		var alias SQL.ValuesListAliasPartial
		alias.Alias = "x"
		alias.Columns = append(alias.Columns, g.sqlInputColumns...)
		alias.Columns = append(alias.Columns, g.sqlInputColumns2...)

		var tail SQL.UpdateTail
		tail.Where = g.buildSQLWhereClause(si)

		g.sqltailnode = SQL.NodeList{alias, tail}
		return stmt
	}

	if si.query.filterField != "" && len(g.outputcolumns) > 0 {
		var tail SQL.UpdateTail
		tail.Returning = SQL.ReturningClause(g.outputcolumns)
		g.sqltailnode = tail
	} else if si.query.dataField.data.isSlice && (len(g.outputcolumns) > 0 || si.query.whereBlock != nil) {
		var tail SQL.UpdateTail
		tail.Where = g.buildSQLWhereClause(si)
		tail.Returning = SQL.ReturningClause(g.outputcolumns)
		g.sqltailnode = tail
	} else {
		stmt.Tail.Where = g.buildSQLWhereClause(si)
		stmt.Tail.Returning = SQL.ReturningClause(g.outputcolumns)
	}

	return stmt
}

// sqlselect builds and returns an SQL.SelectStatement.
func (g *generator) sqlselect(si *targetInfo) (selstmt SQL.SelectStatement) {
	selstmt.Columns = g.outputcolumns // columns
	selstmt.Table = g.sqlrelid(si.query.dataField.relId)
	selstmt.Join = g.sqljoin(si.query.joinBlock)
	selstmt.Where = g.buildSQLWhereClause(si)
	selstmt.Order = g.sqlorderby(si.query)
	selstmt.Limit = g.sqllimit(si.query)
	selstmt.Offset = g.sqloffset(si.query)
	return selstmt
}

// sqldelete builds and returns an SQL.DeleteStatement.
func (g *generator) sqldelete(si *targetInfo) (delstmt SQL.DeleteStatement) {
	delstmt.Table = g.sqlrelid(si.query.dataField.relId)
	delstmt.Using = g.sqlusing(si.query.joinBlock)
	delstmt.Where = g.buildSQLWhereClause(si)
	delstmt.Returning = SQL.ReturningClause(g.outputcolumns) //returning
	return delstmt
}

// sqlselectexists builds and returns an SQL.SelectExistsStatement.
func (g *generator) sqlselectexists(si *targetInfo) (selstmt SQL.SelectExistsStatement) {
	selstmt.Table = g.sqlrelid(si.query.dataField.relId)
	selstmt.Join = g.sqljoin(si.query.joinBlock)
	selstmt.Not = si.query.kind == queryKindSelectNotExists
	if si.query.filterField == "" {
		selstmt.Where = g.buildSQLWhereClause(si)
		selstmt.Order = g.sqlorderby(si.query)
		selstmt.Limit = g.sqllimit(si.query)
		selstmt.Offset = g.sqloffset(si.query)
	} else {
		selstmt.Open = true
		g.fclose = true
	}
	return selstmt
}

// sqlselectcount builds and returns an SQL.SelectCountStatement.
func (g *generator) sqlselectcount(si *targetInfo) (selstmt SQL.SelectCountStatement) {
	selstmt.Table = g.sqlrelid(si.query.dataField.relId)
	selstmt.Join = g.sqljoin(si.query.joinBlock)
	if si.query.filterField == "" {
		selstmt.Where = g.buildSQLWhereClause(si)
		selstmt.Order = g.sqlorderby(si.query)
		selstmt.Offset = g.sqloffset(si.query)
	}
	return selstmt
}

// buildSQLWhereClause builds and returns ...
func (g *generator) buildSQLWhereClause(si *targetInfo) (where SQL.WhereClause) {
	if w := si.query.whereBlock; w != nil {
		sel := GO.SelectorExpr{X: idrecv, Sel: GO.Ident{w.name}}
		where.SearchCondition, _ = g.sqlsearchcond(w.items, sel, false)
	} else if si.query.kind == queryKindUpdate && (si.query.all == false && si.query.filterField == "") {
		var list SQL.BoolValueExprList
		for i, item := range si.info.pkeys {
			p := SQL.ComparisonPredicate{}
			p.Cmp = predicateKindToSQLCmpOp[isEQ]
			p.LPredicand = g.sqlcolref(item.colId)

			if item.sqlparam == nil {
				item.sqlparam = g.sqlparam()
			}
			p.RPredicand = item.sqlparam

			if si.query.dataField.data.isSlice {
				col := SQL.ColumnIdent{Qual: "x", Name: SQL.Name(item.colId.name)}
				p.RPredicand = SQL.CastExpr{Expr: col, Type: item.column.typ.name}
			}

			if i == 0 {
				list.Initial = p
			} else {
				list.Items = append(list.Items, SQL.AND{Operand: p})
			}
		}
		where.SearchCondition = list
	}
	return where
}

func (g *generator) sqlsearchcond(items []*predicateItem, sel GO.SelectorExpr, parenthesized bool) (list SQL.BoolValueExprList, count int) {
	for _, item := range items {
		count += 1

		var x SQL.BoolValueExpr
		switch pred := item.pred.(type) {
		// nested: recurse
		case *predicateNested:
			var ncount int

			sel := GO.SelectorExpr{X: sel, Sel: GO.Ident{pred.name}}
			x, ncount = g.sqlsearchcond(pred.items, sel, true)

			count += ncount - 1

		// 3-arg predicate: build & return
		case *predicateBetween:
			p := SQL.BetweenPredicate{}
			p.Predicand = g.sqlcolref(pred.colId)
			if x, ok := pred.x.(colId); ok {
				p.LowEnd = g.sqlcolref(x)
			} else {
				// assume pred.x is *fieldDatum
				p.LowEnd = g.sqlparam()
			}
			if y, ok := pred.y.(colId); ok {
				p.HighEnd = g.sqlcolref(y)
			} else {
				// assume pred.x is *fieldDatum
				p.HighEnd = g.sqlparam()
			}
			x = p

		// 2-arg predicates: prepare first, then build & return
		case *predicateField, *predicateColumn:
			var (
				lhs      SQL.ValueExpr
				rhs      SQL.ValueExpr
				predKind predicateKind
				qua      quantifier
				field    string
				coltype  string
			)

			// prepare
			switch pred := pred.(type) {
			case *predicateField:
				predKind = pred.kind
				qua = pred.qua
				lhs = g.sqlcolref(pred.colId)
				rhs = g.sqlparam()
				if len(pred.modfunc) > 0 {
					li := SQL.RoutineInvocation{}
					li.Name = string(pred.modfunc)
					li.Args = []SQL.ValueExpr{lhs}
					lhs = li

					ri := SQL.RoutineInvocation{}
					ri.Name = string(pred.modfunc)
					ri.Args = []SQL.ValueExpr{rhs}
					rhs = ri
				}

				if qua > 0 {
					coltype = g.targetInfo.info.colmap[pred].typ.namefmt
				}

				field = pred.name // needed for isin/notin predicates
			case *predicateColumn:
				predKind = pred.kind
				qua = pred.qua
				lhs = g.sqlcolref(pred.colId)
				if !pred.colId2.isEmpty() {
					rhs = g.sqlcolref(pred.colId2)
				} else if len(pred.literal) > 0 {
					rhs = SQL.Literal{pred.literal}
				}
			}

			// quantifier?
			if qua > 0 {
				if len(coltype) > 0 {
					cast := SQL.CastExpr{}
					cast.Expr = rhs
					cast.Type = coltype + "[]"
					rhs = cast
				}
				qx := SQL.QuantifiedExpr{}
				qx.Qua = quantifierToSQLQuantifier[qua]
				qx.Expr = rhs
				rhs = qx
			}

			// build & return
			switch predKind {
			case isEQ, notEQ, notEQ2, isLT, isGT, isLTE, isGTE:
				p := SQL.ComparisonPredicate{}
				p.Cmp = predicateKindToSQLCmpOp[predKind]
				p.LPredicand = lhs
				p.RPredicand = rhs
				x = p
			case isLike, notLike:
				p := SQL.LikePredicate{}
				p.Not = (predKind == notLike)
				p.Predicand = lhs
				p.Pattern = rhs
				x = p
			case isILike, notILike:
				p := SQL.ILikePredicate{}
				p.Not = (predKind == notILike)
				p.Predicand = lhs
				p.Pattern = rhs
				x = p
			case isSimilar, notSimilar:
				p := SQL.SimilarPredicate{}
				p.Not = (predKind == notSimilar)
				p.Predicand = lhs
				p.Pattern = rhs
				x = p
			case isDistinct, notDistinct:
				p := SQL.DistinctPredicate{}
				p.Not = (predKind == notDistinct)
				p.LPredicand = lhs
				p.RPredicand = rhs
				x = p
			case isMatch, isMatchi, notMatch, notMatchi:
				p := SQL.RegexPredicate{}
				p.Op = predicateKindToSQLRegExOp[predKind]
				p.Predicand = lhs
				p.Pattern = rhs
				x = p
			case isIn, notIn:
				sx := GO.SelectorExpr{X: sel, Sel: GO.Ident{field}}
				g.insx = append(g.insx, sx)
				g.nparam -= 1  // ordinal param won't be used directly
				g.asvar = true // queryString should be var not const

				num := strconv.Itoa(len(g.insx))
				arg1 := GO.Ident{"len" + num}
				//arg2 := GO.BinaryExpr{X: GO.Ident{"pos" + num}, Op: GO.BinaryAdd, Y: GO.IntLit(1)}
				arg2 := GO.Ident{"pos" + num}

				call := callinvaluelist
				call.Args = GO.ArgsList{List: GO.ExprList{arg1, arg2}}

				p := SQL.InPredicate{}
				p.Not = (predKind == notIn)
				p.Predicand = lhs
				p.ValueList = SQL.HostValue{GO.RawStringInsertExpr{call}}
				x = p
			case isTrue, notTrue, isFalse, notFalse, isUnknown, notUnknown:
				p := SQL.TruthPredicate{}
				p.Not = (predKind == notTrue || predKind == notFalse || predKind == notUnknown)
				p.Truth = predicateKindToSQLTruth[predKind]
				p.Predicand = lhs
				x = p
			case isNull, notNull:
				p := SQL.NullPredicate{}
				p.Not = (predKind == notNull)
				p.Predicand = lhs
				x = p
			default:
				// no predicate, assume lhs is by itself a boolean value expression
				if p, ok := lhs.(SQL.BoolValueExpr); ok {
					x = p
				}
			}
		}

		switch item.bool {
		default: // initial
			list.Initial = x
		case boolAnd:
			list.Items = append(list.Items, SQL.AND{Operand: x})
		case boolOr:
			list.Items = append(list.Items, SQL.OR{Operand: x})
		}

	}

	if count > 2 {
		list.ListStyle = true
	}

	list.Parenthesized = parenthesized
	return list, count
}

func (g *generator) sqlonconflict(si *targetInfo) (clause *SQL.OnConflictClause) {
	if si.query.onConflictBlock == nil {
		return nil
	}

	clause = new(SQL.OnConflictClause)

	// conflict target
	if len(si.query.onConflictBlock.column) > 0 {
		target := make(SQL.ConflictColumns, len(si.query.onConflictBlock.column))
		for i := 0; i < len(target); i++ {
			target[i] = SQL.Name(si.query.onConflictBlock.column[i].name)
		}
		clause.Target = target
	} else if len(si.query.onConflictBlock.index) > 0 {
		target := SQL.ConflictIndex{}
		target.Expr = si.info.conflictindex.indexpr
		target.Pred = si.info.conflictindex.indpred
		clause.Target = target
	} else if len(si.query.onConflictBlock.constraint) > 0 {
		clause.Target = SQL.ConflictConstraint(si.query.onConflictBlock.constraint)
	}

	// conflict action
	if si.query.onConflictBlock.ignore {
		return clause
	} else if si.query.onConflictBlock.update != nil {
		ux := SQL.UpdateExcluded{}
		if si.query.onConflictBlock.update.all {
			for _, item := range si.info.input {
				if si.skipwrite(item) {
					continue
				}
				ux.Columns = append(ux.Columns, SQL.Name(item.colId.name))
			}
		} else {
			for _, cid := range si.query.onConflictBlock.update.items {
				ux.Columns = append(ux.Columns, SQL.Name(cid.name))
			}
		}

		clause.Action = new(SQL.ConflictAction)
		clause.Action.Update = ux
		clause.Action.Update.Compact = len(ux.Columns) == 1
	}
	return clause
}

func (g *generator) sqlorderby(query *queryStruct) (order SQL.OrderClause) {
	if query.orderByList == nil {
		return order
	}

	for _, item := range query.orderByList.items {
		by := SQL.OrderBy{}
		by.Column = g.sqlcolref(item.colId)
		by.Desc = (item.direction == orderDesc)
		order.List = append(order.List, by)
	}
	return order
}

func (g *generator) sqlfrom(jb *joinBlock) (from SQL.FromClause) {
	if jb == nil {
		return from
	}

	from.List = []SQL.TableExpr{g.sqlrelid(jb.relId)}
	for _, item := range jb.items {
		var join SQL.TableJoin
		join.Type = joinTypeToSQLJoinType[item.joinType]
		join.Rel = g.sqlrelid(item.relId)
		join.Cond = g.sqljoincond(item.predicates)
		from.List = append(from.List, join)
	}
	return from
}

func (g *generator) sqlusing(jb *joinBlock) (using SQL.UsingClause) {
	if jb == nil {
		return using
	}

	using.List = []SQL.TableExpr{g.sqlrelid(jb.relId)}
	for _, item := range jb.items {
		var join SQL.TableJoin
		join.Type = joinTypeToSQLJoinType[item.joinType]
		join.Rel = g.sqlrelid(item.relId)
		join.Cond = g.sqljoincond(item.predicates)
		using.List = append(using.List, join)
	}
	return using
}

func (g *generator) sqljoin(jb *joinBlock) (jc SQL.JoinClause) {
	if jb == nil {
		return jc
	}

	for _, item := range jb.items {
		var join SQL.TableJoin
		join.Type = joinTypeToSQLJoinType[item.joinType]
		join.Rel = g.sqlrelid(item.relId)
		join.Cond = g.sqljoincond(item.predicates)
		jc.List = append(jc.List, join)
	}
	return jc
}

func (g *generator) sqljoincond(items []*predicateItem) (cond SQL.JoinCondition) {
	if len(items) > 0 {
		list, _ := g.sqlsearchcond(items, GO.SelectorExpr{}, false)
		list.ListStyle = false

		cond.SearchCondition = list
	}
	return cond
}

// sqllimit generates and returns an SQL.LimitClause based on the given query's "limit" field.
func (g *generator) sqllimit(query *queryStruct) (limit SQL.LimitClause) {
	if query.limitField != nil {
		if len(query.limitField.name) > 0 {
			limit.Value = g.sqlparam()
		} else if query.limitField.value > 0 {
			limit.Value = SQL.LimitUint(query.limitField.value)
		}
		return limit
	}

	// In case the query doesn't have a "limit" field, but the relation
	// field handles only a single record (i.e. it's not a slice, etc.)
	// then, by default, generate a `LIMIT 1` clause.
	if r := query.dataField.data; !r.isArray && !r.isSlice && !r.isIter {
		limit.Value = SQL.LimitInt(1)
		return limit
	}
	return limit
}

// sqloffset generates and returns an SQL.OffsetClause based on the given query's "offset" field.
func (g *generator) sqloffset(query *queryStruct) (offset SQL.OffsetClause) {
	if query.offsetField != nil {
		if len(query.offsetField.name) > 0 {
			offset.Value = g.sqlparam()
		} else if query.offsetField.value > 0 {
			offset.Value = SQL.OffsetUint(query.offsetField.value)
		}
		return offset
	}
	return offset
}

func (g *generator) sqlrelid(id relId) SQL.Ident {
	return SQL.Ident{
		Name:  SQL.Name(id.name),
		Qual:  id.qual,
		Alias: id.alias,
	}
}

func (g *generator) sqlcolref(id colId) SQL.ColumnReference {
	return SQL.ColumnReference{
		Qual: id.qual,
		Name: SQL.Name(id.name),
	}
}

func (g *generator) sqlparam() SQL.OrdinalParameterSpec {
	g.nparam += 1
	return SQL.OrdinalParameterSpec{g.nparam}
}

// declarevar reports whether the queryString value should be declared as a var or as a const.
func (g *generator) declarevar(si *targetInfo) bool {
	return g.asvar || len(si.query.filterField) > 0 ||
		((si.query.kind == queryKindInsert || si.query.kind == queryKindUpdate) &&
			si.query.dataField.data.isSlice)
}

var overridingKindToSQLOverridingClause = map[overridingKind]SQL.OverridingClause{
	overridingSystem: "SYSTEM",
	overridingUser:   "USER",
}

var predicateKindToSQLCmpOp = map[predicateKind]SQL.CMPOP{
	isEQ:   SQL.EQUAL,
	notEQ:  SQL.NOT_EQUAL,
	notEQ2: SQL.NOT_EQUAL2,
	isLT:   SQL.LESS_THAN,
	isGT:   SQL.GREATER_THAN,
	isLTE:  SQL.LESS_THAN_EQUAL,
	isGTE:  SQL.GREATER_THAN_EQUAL,
}

var predicateKindToSQLRegExOp = map[predicateKind]SQL.REGEXOP{
	isMatch:   SQL.MATCH,
	isMatchi:  SQL.MATCH_CI,
	notMatch:  SQL.NOT_MATCH,
	notMatchi: SQL.NOT_MATCH_CI,
}

var predicateKindToSQLTruth = map[predicateKind]SQL.TRUTH{
	isUnknown:  SQL.UNKNOWN,
	notUnknown: SQL.UNKNOWN,
	isTrue:     SQL.TRUE,
	notTrue:    SQL.TRUE,
	isFalse:    SQL.FALSE,
	notFalse:   SQL.FALSE,
}

var quantifierToSQLQuantifier = map[quantifier]SQL.QUANTIFIER{
	quantAny:  SQL.ANY,
	quantSome: SQL.SOME,
	quantAll:  SQL.ALL,
}

var joinTypeToSQLJoinType = map[joinType]SQL.JoinType{
	joinLeft:  SQL.JoinLeft,
	joinRight: SQL.JoinRight,
	joinFull:  SQL.JoinFull,
	joinCross: SQL.JoinCross,
}

var gotyp2coltyp2converter = map[string]map[string]GO.SelectorExpr{
	gotypbools:   {"boolean[]": GO.SelectorExpr{ /*TODO*/ }},
	gotypstrings: {"text[]": GO.SelectorExpr{X: GO.Ident{"gosql"}, Sel: GO.Ident{"StringSliceToTextArray"}}},
	gotypints: {
		"integer[]":  GO.SelectorExpr{X: GO.Ident{"gosql"}, Sel: GO.Ident{"IntSliceToIntArray"}},
		"smallint[]": GO.SelectorExpr{X: GO.Ident{"gosql"}, Sel: GO.Ident{"IntSliceToIntArray"}},
		"bigint[]":   GO.SelectorExpr{X: GO.Ident{"gosql"}, Sel: GO.Ident{"IntSliceToIntArray"}},
	},
	gotypint8s: {
		"integer[]":  GO.SelectorExpr{ /*TODO*/ },
		"smallint[]": GO.SelectorExpr{ /*TODO*/ },
		"bigint[]":   GO.SelectorExpr{ /*TODO*/ },
	},
	gotypint16s: {
		"integer[]":  GO.SelectorExpr{ /*TODO*/ },
		"smallint[]": GO.SelectorExpr{ /*TODO*/ },
		"bigint[]":   GO.SelectorExpr{ /*TODO*/ },
	},
	gotypint32s: {
		"integer[]":  GO.SelectorExpr{ /*TODO*/ },
		"smallint[]": GO.SelectorExpr{ /*TODO*/ },
		"bigint[]":   GO.SelectorExpr{ /*TODO*/ },
	},
	gotypint64s: {
		"integer[]":  GO.SelectorExpr{ /*TODO*/ },
		"smallint[]": GO.SelectorExpr{ /*TODO*/ },
		"bigint[]":   GO.SelectorExpr{ /*TODO*/ },
	},
}
