// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
	"github.com/frk/gosql/testdata/common"
)

func (q *SelectWithAfterScanSingleQuery) Exec(c gosql.Conn) error {
	const queryString = `SELECT
	u."id"
	, u."email"
	, u."full_name"
	, u."created_at"
	FROM "test_user" AS u
	LIMIT 1` // `

	row := c.QueryRow(queryString)

	q.User = new(common.User2)
	err := row.Scan(
		&q.User.Id,
		&q.User.Email,
		&q.User.FullName,
		&q.User.CreatedAt,
	)
	if err != nil {
		return err
	}

	q.User.AfterScan()
	return nil
}
