// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *SelectCountWithFilterQuery) Exec(c gosql.Conn) error {
	var queryString = `SELECT COUNT(*) FROM "test_user" AS u
	` // `

	queryString += q.Filter.ToSQL()
	params := q.Filter.Params()

	row := c.QueryRow(queryString, params...)
	return row.Scan(&q.Count)
}
