// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
	"github.com/frk/gosql/testdata/common"
)

func (q *SelectWithRecordNestedSliceQuery) Exec(c gosql.Conn) error {
	const queryString = `SELECT
	n."foo_bar_baz_val"
	, n."foo_baz_val"
	, n."foo2_bar_baz_val"
	, n."foo2_baz_val"
	FROM "test_nested" AS n
	` // `

	rows, err := c.Query(queryString)
	if err != nil {
		return err
	}
	defer rows.Close()

	for rows.Next() {
		v := new(common.Nested)
		v.FOO = new(common.Foo)
		v.FOO.Baz = new(common.Baz)
		v.Foo = new(common.Foo)
		v.Foo.Baz = new(common.Baz)
		err := rows.Scan(
			&v.FOO.Bar.Baz.Val,
			&v.FOO.Baz.Val,
			&v.Foo.Bar.Baz.Val,
			&v.Foo.Baz.Val,
		)
		if err != nil {
			return err
		}

		q.Nesteds = append(q.Nesteds, v)
	}
	return rows.Err()
}
