// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
	"github.com/frk/gosql/testdata/common"
)

func (q *SelectWithWhereBlockNestedQuery) Exec(c gosql.Conn) error {
	const queryString = `SELECT
	u."id"
	, u."email"
	, u."full_name"
	, u."created_at"
	FROM "test_user" AS u
	WHERE u."full_name" LIKE $1
	AND u."created_at" > $2
	OR (u."full_name" LIKE $3 AND u."created_at" < $4)` // `

	rows, err := c.Query(queryString,
		q.Where.FullName,
		q.Where.CreatedAfter,
		q.Where.Or.FullName,
		q.Where.Or.CreatedBefore,
	)
	if err != nil {
		return err
	}
	defer rows.Close()

	for rows.Next() {
		v := new(common.User)
		err := rows.Scan(
			&v.Id,
			&v.Email,
			&v.FullName,
			&v.CreatedAt,
		)
		if err != nil {
			return err
		}

		q.Users = append(q.Users, v)
	}
	return rows.Err()
}
