// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *InsertBasicSingleQuery) Exec(c gosql.Conn) error {
	const queryString = `INSERT INTO "test_user" AS u (
		"id"
		, "email"
		, "full_name"
		, "created_at"
	) VALUES (
		$1
		, $2
		, $3
		, $4
	)` // `

	_, err := c.Exec(queryString,
		q.User.Id,
		q.User.Email,
		q.User.FullName,
		q.User.CreatedAt,
	)
	return err
}
