// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *InsertSingleDefaultQuery) Exec(c gosql.Conn) error {
	const queryString = `INSERT INTO "test_user" AS u (
		"email"
		, "password"
		, "created_at"
		, "updated_at"
	) VALUES (
		$1
		, DEFAULT
		, $2
		, $3
	)` // `

	_, err := c.Exec(queryString,
		q.User.Email,
		q.User.CreatedAt,
		q.User.UpdatedAt,
	)
	return err
}
