// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *InsertJSONSingleQuery) Exec(c gosql.Conn) error {
	const queryString = `INSERT INTO "test_user" AS u (
		"email"
		, "full_name"
		, "is_active"
		, "metadata1"
		, "metadata2"
		, "created_at"
		, "updated_at"
	) VALUES (
		$1
		, $2
		, $3
		, $4
		, $5
		, $6
		, $7
	)` // `

	_, err := c.Exec(queryString,
		q.User.Email,
		q.User.FullName,
		q.User.IsActive,
		gosql.JSON(q.User.Metadata1),
		gosql.JSON(q.User.Metadata2),
		q.User.CreatedAt,
		q.User.UpdatedAt,
	)
	return err
}
