// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
	"github.com/frk/gosql/pgsql"
)

func (q *InsertReturningAllJSONSingleQuery) Exec(c gosql.Conn) error {
	const queryString = `INSERT INTO "test_user" AS u (
		"email"
		, "full_name"
		, "is_active"
		, "metadata1"
		, "metadata2"
		, "created_at"
		, "updated_at"
	) VALUES (
		$1
		, $2
		, $3
		, $4
		, $5
		, $6
		, $7
	)
	RETURNING
	u."id"
	, u."email"
	, u."full_name"
	, u."is_active"
	, u."metadata1"
	, u."metadata2"
	, u."created_at"
	, u."updated_at"` // `

	row := c.QueryRow(queryString,
		q.User.Email,
		q.User.FullName,
		q.User.IsActive,
		pgsql.JSON(q.User.Metadata1),
		pgsql.JSON(q.User.Metadata2),
		q.User.CreatedAt,
		q.User.UpdatedAt,
	)
	return row.Scan(
		&q.User.Id,
		&q.User.Email,
		&q.User.FullName,
		&q.User.IsActive,
		pgsql.JSON(&q.User.Metadata1),
		pgsql.JSON(&q.User.Metadata2),
		&q.User.CreatedAt,
		&q.User.UpdatedAt,
	)
}
