// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *InsertWithRowsAffectedErrorInfoHandlerQuery) Exec(c gosql.Conn) error {
	const queryString = `INSERT INTO "test_user" AS u (
		"email"
		, "password"
		, "created_at"
		, "updated_at"
	) VALUES (
		$1
		, $2
		, $3
		, $4
	)` // `

	res, err := c.Exec(queryString,
		q.User.Email,
		q.User.Password,
		q.User.CreatedAt,
		q.User.UpdatedAt,
	)
	if err != nil {
		return q.ErrorInfoHandler.HandleErrorInfo(&gosql.ErrorInfo{Error: err, Query: queryString, SpecKind: "Insert", SpecName: "InsertWithRowsAffectedErrorInfoHandlerQuery", SpecValue: q})
	}
	i64, err := res.RowsAffected()
	if err != nil {
		return q.ErrorInfoHandler.HandleErrorInfo(&gosql.ErrorInfo{Error: err, Query: queryString, SpecKind: "Insert", SpecName: "InsertWithRowsAffectedErrorInfoHandlerQuery", SpecValue: q})
	}

	q.RowsAffected = int(i64)
	return nil
}
