// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"time"
)

var _FilterBasicRecords_colmap = map[string]string{
	"Id":        `"id"`,
	"Email":     `"email"`,
	"FullName":  `"full_name"`,
	"CreatedAt": `"created_at"`,
}

func (f *FilterBasicRecords) Init() {
	f.Filter.Init(_FilterBasicRecords_colmap, "")
}

func (f *FilterBasicRecords) Id(op string, val int) *FilterBasicRecords {
	f.Filter.Col(`"id"`, op, val)
	return f
}

func (f *FilterBasicRecords) Email(op string, val string) *FilterBasicRecords {
	f.Filter.Col(`"email"`, op, val)
	return f
}

func (f *FilterBasicRecords) FullName(op string, val string) *FilterBasicRecords {
	f.Filter.Col(`"full_name"`, op, val)
	return f
}

func (f *FilterBasicRecords) CreatedAt(op string, val time.Time) *FilterBasicRecords {
	f.Filter.Col(`"created_at"`, op, val)
	return f
}

func (f *FilterBasicRecords) And(nest func(*FilterBasicRecords)) *FilterBasicRecords {
	if nest == nil {
		f.Filter.And(nil)
		return f
	}
	f.Filter.And(func() {
		nest(f)
	})
	return f
}

func (f *FilterBasicRecords) Or(nest func(*FilterBasicRecords)) *FilterBasicRecords {
	if nest == nil {
		f.Filter.Or(nil)
		return f
	}
	f.Filter.Or(func() {
		nest(f)
	})
	return f
}
