// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"time"
)

var _FilterWithExcludeRecords_colmap = map[string]string{
	"Id":        `"id"`,
	"Email":     `"email"`,
	"CreatedAt": `"created_at"`,
	"UpdatedAt": `"updated_at"`,
}

func (f *FilterWithExcludeRecords) Init() {
	f.Filter.Init(_FilterWithExcludeRecords_colmap, "")
}

func (f *FilterWithExcludeRecords) Id(op string, val int) *FilterWithExcludeRecords {
	f.Filter.Col(`"id"`, op, val)
	return f
}

func (f *FilterWithExcludeRecords) Email(op string, val string) *FilterWithExcludeRecords {
	f.Filter.Col(`"email"`, op, val)
	return f
}

func (f *FilterWithExcludeRecords) CreatedAt(op string, val time.Time) *FilterWithExcludeRecords {
	f.Filter.Col(`"created_at"`, op, val)
	return f
}

func (f *FilterWithExcludeRecords) UpdatedAt(op string, val time.Time) *FilterWithExcludeRecords {
	f.Filter.Col(`"updated_at"`, op, val)
	return f
}

func (f *FilterWithExcludeRecords) And(nest func(*FilterWithExcludeRecords)) *FilterWithExcludeRecords {
	if nest == nil {
		f.Filter.And(nil)
		return f
	}
	f.Filter.And(func() {
		nest(f)
	})
	return f
}

func (f *FilterWithExcludeRecords) Or(nest func(*FilterWithExcludeRecords)) *FilterWithExcludeRecords {
	if nest == nil {
		f.Filter.Or(nil)
		return f
	}
	f.Filter.Or(func() {
		nest(f)
	})
	return f
}
