// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"time"
)

var _FilterTextSearchRecords_colmap = map[string]string{
	"Id":        `u."id"`,
	"Email":     `u."email"`,
	"FullName":  `u."full_name"`,
	"CreatedAt": `u."created_at"`,
}

func (f *FilterTextSearchRecords) Init() {
	f.FilterMaker.Init(_FilterTextSearchRecords_colmap, `u."_search_document"`)
}

func (f *FilterTextSearchRecords) Id(op string, val int) *FilterTextSearchRecords {
	f.FilterMaker.Col(`u."id"`, op, val)
	return f
}

func (f *FilterTextSearchRecords) Email(op string, val string) *FilterTextSearchRecords {
	f.FilterMaker.Col(`u."email"`, op, val)
	return f
}

func (f *FilterTextSearchRecords) FullName(op string, val string) *FilterTextSearchRecords {
	f.FilterMaker.Col(`u."full_name"`, op, val)
	return f
}

func (f *FilterTextSearchRecords) CreatedAt(op string, val time.Time) *FilterTextSearchRecords {
	f.FilterMaker.Col(`u."created_at"`, op, val)
	return f
}

func (f *FilterTextSearchRecords) And(nest func(*FilterTextSearchRecords)) *FilterTextSearchRecords {
	if nest == nil {
		f.FilterMaker.And(nil)
		return f
	}
	f.FilterMaker.And(func() {
		nest(f)
	})
	return f
}

func (f *FilterTextSearchRecords) Or(nest func(*FilterTextSearchRecords)) *FilterTextSearchRecords {
	if nest == nil {
		f.FilterMaker.Or(nil)
		return f
	}
	f.FilterMaker.Or(func() {
		nest(f)
	})
	return f
}
