// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *DeleteWithWhereBlock2Query) ExecQuery(c gosql.Conn) error {
	const queryString = `DELETE FROM "test_user"
	WHERE "created_at" > $1
	AND "created_at" < $2
	AND ("full_name" = 'John Doe' OR "full_name" = 'Jane Doe')` // `

	_, err := c.Exec(queryString, q.Where.CreatedAfter, q.Where.CreatedBefore)
	return err
}
