// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *DeleteWithRowsAffectedQuery) Exec(c gosql.Conn) error {
	const queryString = `DELETE FROM "test_user" AS u
	WHERE u."created_at" < $1` // `

	res, err := c.Exec(queryString, q.Where.CreatedBefore)
	if err != nil {
		return err
	}
	i64, err := res.RowsAffected()
	if err != nil {
		return err
	}

	q.RowsAffected = int(i64)
	return nil
}
