// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *UpdateFromblockJoinSingleQuery) Exec(c gosql.Conn) error {
	const queryString = `UPDATE "test_user" AS u SET (
		"email"
		, "full_name"
		, "is_active"
		, "created_at"
		, "updated_at"
	) = (
		$1
		, $2
		, $3
		, $4
		, $5
	)
	FROM "test_post" AS p
	LEFT JOIN "test_join1" AS j1 ON j1."post_id" = p."id"
	RIGHT JOIN "test_join2" AS j2 ON j2."join1_id" = j1."id"
	FULL JOIN "test_join3" AS j3 ON j3."join2_id" = j2."id"
	CROSS JOIN "test_join4" AS j4
	WHERE u."id" = p."user_id" AND p."is_spam" IS TRUE` // `

	_, err := c.Exec(queryString,
		q.User.Email,
		q.User.FullName,
		q.User.IsActive,
		q.User.CreatedAt,
		q.User.UpdatedAt,
	)
	return err
}
