// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *UpdateFromblockBasicSingleQuery) Exec(c gosql.Conn) error {
	const queryString = `UPDATE "test_user" AS u SET (
		"email"
		, "full_name"
		, "is_active"
		, "created_at"
		, "updated_at"
	) = (
		$1
		, $2
		, $3
		, $4
		, $5
	)
	FROM "test_post" AS p
	WHERE u."id" = p."user_id" AND p."is_spam" IS TRUE` // `

	_, err := c.Exec(queryString,
		q.User.Email,
		q.User.FullName,
		q.User.IsActive,
		q.User.CreatedAt,
		q.User.UpdatedAt,
	)
	return err
}
