// DO NOT EDIT. This file was generated by "github.com/frk/gosql".

package testdata

import (
	"github.com/frk/gosql"
)

func (q *UpdateWhereblockReturningAllSingleQuery) Exec(c gosql.Conn) error {
	const queryString = `UPDATE "test_user" AS u SET (
		"email"
		, "full_name"
		, "is_active"
		, "created_at"
		, "updated_at"
	) = (
		$1
		, $2
		, $3
		, $4
		, $5
	)
	WHERE u."id" = $6
	RETURNING
	u."id"
	, u."email"
	, u."full_name"
	, u."is_active"
	, u."created_at"
	, u."updated_at"` // `

	row := c.QueryRow(queryString,
		q.User.Email,
		q.User.FullName,
		q.User.IsActive,
		q.User.CreatedAt,
		q.User.UpdatedAt,
		q.Where.Id,
	)
	return row.Scan(
		&q.User.Id,
		&q.User.Email,
		&q.User.FullName,
		&q.User.IsActive,
		&q.User.CreatedAt,
		&q.User.UpdatedAt,
	)
}
